Repository JaeAeich/CampusHub, pull requests merged in 2024-04, with the labels that each got.

#190 fix: frontend improve
  client/src/App.tsx
  client/src/components/ProductDetails.tsx
  client/src/components/ServiceCards.tsx
  client/src/components/StoreInventory.tsx
  client/src/utils/fileUpload.ts
Labels: size/XL

#194 feat: push notification
  .github/workflows/e2e-ci.yaml
  .gitignore
  client/.env.sample
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Cart.tsx
  client/src/components/Navbar.tsx
  client/src/components/Notifications.tsx
  client/src/components/ProfileButton.tsx
  client/src/store/notification/notificationSlice.ts
  client/src/store/store.ts
  docker-compose.yaml
  notification_server/.env.sample
  notification_server/Dockerfile
  notification_server/index.js
  notification_server/package-lock.json
  notification_server/package.json
  push.env.sample
Labels: size/L

#197 feat: community store done
  client/src/components/ProductsPage.tsx
  client/src/components/ServiceCards.tsx
Labels: size/M

#196 chore: recommendation engine demo
  .gitignore
  client/app/constants.ts
  client/public/products/chips.jpg
  client/public/products/moisturizer.jpg
  client/src/api/products/products.ts
  client/src/api/reviews/reviews.ts
  client/src/components/DealOfTheDay.tsx
  client/src/components/Landing.tsx
  client/src/components/ServiceCards.tsx
  client/src/components/TopPicks.tsx
  client/src/components/TrendingStores.tsx
  server/.gitignore
  server/campus_hub/controllers/precompute.py
  server/campus_hub/controllers/precomputed_recommendations.csv
  server/campus_hub/controllers/products.py
  server/campus_hub/controllers/reviews.py
  server/campus_hub/controllers/users.py
  server/campus_hub/models/user.py
  server/campus_hub/specs/api.yaml
  server/campus_hub/utils/recommendationEngine/recommendationEngine.py
  server/mypy.ini
  server/poetry.lock
  server/pyproject.toml
Labels: size/XL

#184 feat: make review card component
  client/src/api/products/products.ts
  client/src/api/reviews/reviews.ts
  client/src/api/reviews/types.d.ts
  client/src/components/AccountDetails.tsx
  client/src/components/ProductPage.tsx
  client/src/components/ReviewCard.tsx
  client/src/components/Reviews.tsx
  server/campus_hub/controllers/products.py
  server/campus_hub/controllers/reviews.py
  server/campus_hub/controllers/users.py
  server/campus_hub/specs/api.yaml
Labels: size/L

#77 feat: pagination
  client/src/api/stores/stores.ts
  client/src/components/ProductCard.tsx
  client/src/components/ProductsPage.tsx
  client/src/components/StoreInventory.tsx
  client/src/components/ui/pagination.tsx
  server/campus_hub/controllers/products.py
  server/campus_hub/controllers/stores.py
  server/campus_hub/specs/api.yaml
  server/campus_hub/utils/db.py
Labels: size/L

#198 fix: cart getting empty when payment failed
  client/src/App.tsx
  client/src/components/Cart.tsx
  client/src/components/DealOfTheDay.tsx
  client/src/components/Navbar.tsx
  client/src/components/Orders.tsx
  client/src/components/ProductsPage.tsx
  client/src/components/ProfileButton.tsx
  client/src/components/StoreOrderList.tsx
  client/src/components/TopPicks.tsx
  client/src/components/UserProfile.tsx
  server/campus_hub/controllers/precomputed_recommendations.csv
Labels: size/L
